
public class p2 {
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    // By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    
    public static void main(String [ ] args){
        System.out.println(solution());

    }
    
    // Solving thought process
    
    // 1. Notice each number is sum of 2 numbers before and each number even = even + even or odd + odd.
    // only happens each 3 times since start with 2 odd.
    
    public static int solution(){
        int a = 3;
        int b = 5;
        int c = 8;
        int res = 2;
        while(c < 4000000) {
            res += c;
            a = b+c;
            b = a+c;
            c = a+b;
        }
        return res;
    }
}
